### ISSUE TITLE
Reading file content

### ISSUE THREAD

**Issue by Stan-Cho** [MichelleWuSi5/cosimlog_parser#4]
https://github.com/MichelleWuSi5/cosimlog_parser/blob/4ff8ddc35fe5af05051233b24ab64e61262ed323/instruction_count.py#L57

How about changing this line to `for line in fp:`?
I think it would save more memory than reading all lines into a list when processing a large file. Correct me if I am wrong.

**Comment by MichelleWuSi5** [comment]
Good idea.
I had a try and it works for me. Thanks!
