### ISSUE TITLE
Some coding change

### ISSUE THREAD

**Issue by apua** [MichelleWuSi5/cosimlog_parser#5]
`encoding = 'utf-8'` is unnecessary because `decode` default refer to OS environment which is UTF-8 usually. Remove it to reduce code complexity

line 12~13 `proj` and `tmp1` leave the main code too far to read. They are not constant, no need to the top of script

While you don't need ordering, consider leave `unique` return `set` object.
While `unique` is called only once, it doesn't have to be wrapped into function.
To calculate amount for line 86, `unique_instruction_count = len(set(...))` is enough to represent.

line 85, avoid using f-string on literal string

line 79 `debug_level` is not what it works like.
If you need multi-line comment, seeking the way on your IDE (Vim or VS Code)

Avoid one liner for loop on product code; if you wanna clear and short print your list as you did, consider the usage of `print` function such as `print(*your_list[0:5], sep='\n')`

line 42~45, simply `return n == 4`

In the cases of `get_inst_code_list`, `get_inst_cmd_list`, `check_privilege`, it is good to use regexp to represent the pattern you would like to match.
However, if it is not comfortable to leverage regexp, you could add "docstring" on each function to describe which string form you considered.

line 5, It suggests to leave each `import` statement on separated line in product code.

A personal suggestion about "comment" coding style is, leave one space after '#' sign, in order to distinguish which comment is your words from commented code.

**Comment by apua** [comment]
You could call me later to explain what I talk about.

**Comment by timhsu404** [comment]
@MichelleWuSi5 @apua 
Another way to print list in one line.
```
print("\n".join(your_list[0:5]))
```
I'll prefer this because it is just a string operation.
It will be more flexible then unpack list version, the method that changed the print behavior.

**Comment by apua** [comment]
@MichelleWuSi5 while you and me have reviewed it, it is fine to close this issue, up to you.
