### ISSUE TITLE
for-loop style

### ISSUE THREAD

**Issue by EricCheng2222** [MichelleWuSi5/cosimlog_parser#6]
Maybe it's just me, but even there's only one line after for-loop, I'll change line, instead of putting everything in one line.

**Comment by EricCheng2222** [comment]
if you like one-liner, maybe you can take a look at "map"

**Comment by timhsu404** [comment]
Duplicated for #5.

**Comment by MichelleWuSi5** [comment]
That's good point, let me check again and fix it.
